import { Injectable } from '@nestjs/common';

@Injectable()
export class ConstantService {
  public GLOBAL_CONST = Object.freeze({
    AMOUNT_UNITS: Object.freeze({
      KLC: 'klocalcurrency',
      KEURO: 'keuros',
      KEURO_SALES: 'keurossales',
      MD: 'mandays',
    }),
    QUEUE: Object.freeze({
      PYRAMID_QUEUE: Object.freeze({
        NAME: 'PYRAMID',
        SEPARATOR: ';',
        HEADER: [
          'Ressource_Staff_Type',
          'Ressource_CDS',
          'Ressource_CSM',
          'Client_Entity',
          'portfolio_sub_portfolio',
          'plan',
          'activity_Type',
          'actuals_md',
          'etc_eac_ke',
          'etc_eac',
          'actuals_eac',
          'actuals_eac_ke',
          'partner_actuals',
          'payor_actuals',
          'partner_etc',
          'payor_etc',
          'Month_Monthly_report',
        ],
      }),
      NOSICA_QUEUE: Object.freeze({
        NAME: 'NOSICA',
        SEPARATOR: ';',
        HEADER: [
          'fiscal_year',
          'accounting_period',
          'code_dept_local',
          'type_dept_local',
          'code_entity_conso',
          'code_entity_local',
          'code_entity_elr',
          'data_type_code',
          'code_bank',
          'code_guichet',
          'code_pci',
          'code_account_local',
          'code_gop',
          'code_currency_base',
          'code_currency_transaction',
          'code_ledger',
          'code_object',
          'code_product',
          'code_affiliate',
          'code_ifrs_prc',
          'code_pcec',
          'account_type',
          'back_office_data_source',
          'ytd_amount_base_currency_wo_adjust',
          'ytd_amount_trans_currency_wo_adjust',
          'ytd_amount_eur_currency_wo_adjust',
          'ytd_amount_base_currency_wi_adjust',
          'ytd_amount_trans_currency_wi_adjust',
          'ytd_amount_eur_currency_wi_adjust',
          'ytd_amount_base_currency_wi_adjust_after_comp',
          'ytd_amount_trans_currency_wi_adjust_after_compl',
          'ytd_amount_eur_currency_wi_adjust_after_compl',
          'source_code',
          'situation_date',
          'sprias',
          'insert_date',
          'update_date',
          'shortname',
        ],
      }),
    }),
  });
}
