import { Global } from '@nestjs/common';

@Global()
export class ConstantService {
  public GLOBAL_CONST = Object.freeze({
    AMOUNT_UNITS: Object.freeze({
      KLC: 'klocalcurrency',
      KEURO: 'keuros',
      KEURO_SALES: 'keurossales',
      MD: 'mandays',
    }),
    SCOPES: Object.freeze({
      IRBS: 1,
      BSC: 2,
    }),
    CRON_INTERVAL: '1 hours', // One hours
    QUEUE: Object.freeze({
      PYRAMID_QUEUE: Object.freeze({
        NAME: 'PYRAMID',
        ORIGIN_SEPARATOR: '\\|@\\|',
        SEPARATOR: ';',
        HEADER: [
          'Project_Code',
          'Project_Name',
          'Activity_Application',
          'Activity_Application_Label',
          'curve_type',
          'eac',
          'eac_ke',
          'CDS',
          'CSM',
          'PARENT_DESCR',
          'staff_type',
          'activity_plan',
          'activity_type',
          'portfolio',
          'sub_portfolio',
          'partner',
          'code_ca_payor',
          'payor',
          'Client_Entity',
          'pyr_tmp_month_mr',
        ],
      }),
      PYRAMIDACTUALS_QUEUE: Object.freeze({
        NAME: 'PYRAMIDACTUALS',
        ORIGIN_SEPARATOR: '\\|@\\|',
        SEPARATOR: ';',
        HEADER: [
          'resource_igg',
          'resource_first_name',
          'resource_type',
          'resource_last_name',
          'resource_location',
          'resource_staff_type_description',
          'ressource_staff_type',
          'ressource_cds',
          'ressource_csm',
          'ressource_team',
          'ressource_sub_team',
          'client_entity',
          'month_timetracking',
          'year_timetracking',
          'project_code',
          'schedule_name',
          'portfolio_owner',
          'portfolio_sub_portfolio',
          'sub_portfolio',
          'schedule_manager',
          'axe',
          'plan',
          'activity_type',
          'wbs_element_name',
          'task_name',
          'owner',
          'payor',
          'label_payor',
          'partner',
          'application',
          'standard_actuals_md',
          'overtime_actuals_h',
          'stand_by_actuals_h',
          'overtime_actuals_md',
          'stand_by_actuals_md',
          'standard_actuals_input_md',
          'standard_actuals_broadcasted_md',
          'standard_actuals_validated_md',
          'standard_actuals_integrated_md',
          'overtime_actuals_input_h',
          'overtime_actuals_broadcasted_h',
          'overtime_actuals_validated_h',
          'overtime_actuals_integrated_h',
          'stand_by_actuals_input_h',
          'stand_by_actuals_broadcasted_h',
          'stand_by_actuals_validated_h',
          'stand_by_actuals_integrated_h',
          'overtime_actuals_input_md',
          'overtime_actuals_broadcasted_md',
          'overtime_actuals_validated_md',
          'overtime_actuals_integrated_md',
          'stand_by_actuals_input_md',
          'stand_by_actuals_broadcasted_md',
          'stand_by_actuals_validated_md',
          'actuals_integrated_md',
          'month_monthly_report',
          'free_text_1',
          'free_text_2',
          'free_text_3',
          'free_text_4',
          'free_text_5',
        ],
      }),
      NOSICA_QUEUE: Object.freeze({
        NAME: 'NOSICA',
        ORIGIN_SEPARATOR: '\\|@\\|',
        SEPARATOR: ';',
        HEADER: [
          'fiscal_year',
          'accounting_period',
          'code_guichet',
          'code_currency_base',
          'code_ledger',
          'situation_date',
          'code_snrg',
          'insert_date',
          'cds',
          'ytd_amount_base_currency_wo_adjust',
          'ytd_amount_trans_currency_wo_adjust',
          'ytd_amount_eur_currency_wo_adjust',
          'ytd_amount_base_currency_wi_adjust',
          'ytd_amount_trans_currency_wi_adjust',
          'ytd_amount_eur_currency_wi_adjust',
          'ytd_amount_base_currency_wi_adjust_after_comp',
          'ytd_amount_trans_currency_wi_adjust_after_compl',
          'ytd_amount_eur_currency_wi_adjust_after_compl',
        ],
      }),
    }),
  });
}
